### PR TITLE
Fixed folders name @cd (...)

### PR DESCRIPTION
**Pull request by Simonmicro**
* Description of what the PR does, such as fixes # {issue number}
Because you clone from (...)/mimic1.git git will clone to the folder mimic1.
I've changed the command to match the folders name again.

* Description of how to validate or test this PR
~

* Whether you have signed a CLA (Contributor Licensing Agreement)
I guess it is not necessary for THAT MASSIVE pull request...

### CODE REVIEW

**Comment by forslund** [comment]
Thanks for noticing and fixing @Simonmicro.

The CLA is necessary however. We require it for all pull requests since it's tricky to draw the line for what's acceptable without CLA. Basically the CLA protects yourself, the project, and users of Mycroft technologies and makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

The CLA process is relatively easy and a one-time thing so for future contributions you're going to be all set :) Please visit https://mycroft.ai/cla to sign it.

**Comment by Simonmicro** [comment]
I simply hate to read legal stuff - but whatever: It's signed (and completely read through).

**Comment by forslund** [comment]
Thanks, waiting for conformation and then I'll merge this.

**Comment by krisgesling** [comment]
Hey, just noticed that the CLA is in the system, so merging this.

Sorry for the delay Simon, but still appreciate the contribution :)

**Pull request merged**
